#!/bin/bash
# Install (or update) the weekly consolidation report as a LaunchAgent on this Mac.
#
# TCC constraint: launchd cannot reliably execute anything under ~/Desktop (macOS
# privacy protection — the same constraint that forced the subscription-monitor
# job out of ~/Desktop). This repo's checkout lives under ~/Desktop/project/, so
# the plist must never point into it: this script copies the runner to
# $INSTALL_DIR (default ~/.local/share/asaki-memory/weekly-runner/) and points the
# plist there. The repo copy stays the source of truth — re-run this script after
# every change to the runner.
#
# Usage:  ASAKI_MEMORY_BASE_URL=https://... bash integrations/local/install-weekly-launchagent.sh
set -euo pipefail

LABEL="com.asaki.memory.weekly-report"
INSTALL_DIR="${ASAKI_MEMORY_INSTALL_DIR:-$HOME/.local/share/asaki-memory/weekly-runner}"
LOG_DIR="${ASAKI_MEMORY_LOG_DIR:-$HOME/.local/state/asaki-memory/logs}"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/weekly-consolidation-report.sh"

BASE_URL="${ASAKI_MEMORY_BASE_URL:-}"
if [ -z "$BASE_URL" ]; then
  echo "ASAKI_MEMORY_BASE_URL must be set (the Worker endpoint; not stored in this repo)" >&2
  exit 1
fi

mkdir -p "$INSTALL_DIR" "$LOG_DIR" "$HOME/Library/LaunchAgents"
install -m 755 "$SRC" "$INSTALL_DIR/weekly-consolidation-report.sh"

cat > "$PLIST" <<PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
  Generated by integrations/local/install-weekly-launchagent.sh in the
  asaki-memory-manager repo. Do not hand-edit; re-run the installer instead.
  No credential appears here: the runner reads ASAKI_MEMORY_API_KEY out of the
  captain's login fish environment at run time.
-->
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>$LABEL</string>
	<key>ProgramArguments</key>
	<array>
		<string>/bin/bash</string>
		<string>$INSTALL_DIR/weekly-consolidation-report.sh</string>
	</array>
	<key>WorkingDirectory</key>
	<string>$INSTALL_DIR</string>
	<key>EnvironmentVariables</key>
	<dict>
		<key>ASAKI_MEMORY_BASE_URL</key>
		<string>$BASE_URL</string>
		<key>PATH</key>
		<string>$HOME/.local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
	</dict>
	<key>StartCalendarInterval</key>
	<array>
		<dict>
			<key>Weekday</key>
			<integer>1</integer>
			<key>Hour</key>
			<integer>9</integer>
			<key>Minute</key>
			<integer>30</integer>
		</dict>
	</array>
	<key>RunAtLoad</key>
	<false/>
	<key>StandardOutPath</key>
	<string>$LOG_DIR/weekly-report.out.log</string>
	<key>StandardErrorPath</key>
	<string>$LOG_DIR/weekly-report.err.log</string>
	<key>ProcessType</key>
	<string>Background</string>
</dict>
</plist>
PLISTEOF

launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST"
echo "installed: $PLIST -> $INSTALL_DIR/weekly-consolidation-report.sh"
echo "run once now: launchctl kickstart -p gui/$(id -u)/$LABEL"
