// Build the standalone Pi extension package (ROADMAP: lightweight integration).
//
// The Pi extension integrations/pi/asaki-memory.ts is self-contained — it only imports
// Pi host modules (@earendil-works/*, typebox) and node builtins, never anything from src/.
// Installing it via `pi install git:<this monorepo>` would clone the whole backend repo
// (Pi git sources have no subpath support). Instead we publish just the single file as an
// npm package so `pi install npm:<pkg>` pulls a tiny tarball.
//
// Source of truth stays at integrations/pi/asaki-memory.ts (single dev copy — no fork). This
// script only stages a publish dir; run it before `npm publish`.
//
// Usage:
//   npm run build:pi              # stage dist/pi-package/
//   cd dist/pi-package && npm publish
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'dist', 'pi-package');
const SOURCE = join(ROOT, 'integrations', 'pi', 'asaki-memory.ts');

// Change this before your first publish; the name is locked once published to npm.
const PKG_NAME = process.env.PI_PACKAGE_NAME || '@asaki14/pi-memory';

const rootPkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf-8')) as Record<string, any>;

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

cpSync(SOURCE, join(OUT, 'asaki-memory.ts'));

const pkg = {
  name: PKG_NAME,
  version: rootPkg.version,
  description: 'Asaki personal memory for the Pi coding agent (Cloudflare-backed). Standalone Pi extension package.',
  keywords: ['pi-package', 'pi-extension', 'ai-memory'],
  license: rootPkg.license ?? 'MIT',
  repository: rootPkg.repository,
  pi: { extensions: ['./asaki-memory.ts'] },
  // Provided by the Pi host runtime — declared as peers so the tarball stays tiny and Pi
  // resolves them from its own install.
  peerDependencies: {
    '@earendil-works/pi-coding-agent': '*',
    '@earendil-works/pi-tui': '*',
    typebox: '*',
  },
  files: ['asaki-memory.ts', 'README.md'],
};

writeFileSync(join(OUT, 'package.json'), JSON.stringify(pkg, null, 2) + '\n');

const readme = `# ${PKG_NAME}

Standalone [Pi](https://github.com/earendil-works/pi) extension for Asaki personal memory,
backed by a Cloudflare Worker. No repo checkout required.

## Install

\`\`\`bash
pi install npm:${PKG_NAME}
\`\`\`

## Configure

The extension reads its backend URL and admin key from the environment or
\`~/.asaki-memory.json\` (never hardcoded). Set:

\`\`\`bash
export ASAKI_MEMORY_BASE_URL="https://your-worker-subdomain.workers.dev"
export ASAKI_MEMORY_API_KEY="your-admin-api-key"
\`\`\`

or \`~/.asaki-memory.json\`:

\`\`\`json
{ "baseUrl": "https://your-worker-subdomain.workers.dev", "apiKey": "your-admin-api-key", "userId": "asaki" }
\`\`\`

Source of truth lives in the [asaki-memory-manager](${rootPkg.repository?.url ?? ''}) monorepo
at \`integrations/pi/asaki-memory.ts\`; this package is generated by \`npm run build:pi\`.
`;

writeFileSync(join(OUT, 'README.md'), readme);

console.log(`Staged Pi package "${PKG_NAME}" v${rootPkg.version} at ${OUT}`);
console.log('Next: cd dist/pi-package && npm publish   (or test first: pi install ./dist/pi-package)');
